spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
        use_sql_comments: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=Asia/Seoul
    username: root
    password: 1234


mybatis:
  type-aliases-package: com.sb.firstboot.domain
  mapper-locations: classpath:/mapper/*.xml
