spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=Asia/Seoul
    username: root
    password: "!Korea8080"
  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations: file:///c:/Temp/upload/
      add-mappings: true
  servlet:
    multipart:
      location: c:/Temp/upload/
      max-file-size: 10MB
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.sb.firstboot.domain
  mapper-locations: classpath:/mapper/*.xml
