spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytododb?serverTimezone=Asia/Seoul
    username: root
    password: 1234
mybatis:
  type-aliases-package: com.sb.mybatis.model
  mapper-locations: classpath:mapper/**/*-mapper.xml


